### ISSUE TITLE
Class not found exception for RmObjectJsonDeSerializer

### ISSUE THREAD

**Issue by Xelpha** [ehrbase/ehrbase_client_library#28] opened 2020-04-26 18:01 UTC
Calling the createObjectMapper function in "DefaultRestClient" class triggers a class not found exception for RmObjectJsonDeSerializer. This is dependent on the ehrbase jar. It would be good for the sub dependencies to be loaded with it's dependencies.

**Comment by stefanspiska** [comment] 2020-04-27 06:46
This sound like a duplicate of https://github.com/ehrbase/ehrbase_client_library/issues/21
for me

**Closed** 2020-05-02 18:37 UTC
